name: Docker Build Image CI and deploy to nonprod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_APP_NAME: arelle
  AZURE_GROUP: rg-nonprod

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Release Version
      run: echo "RELVER=${{ github.event.release.tag_name }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/awtherllc/arelle:$RELVER
    - name: Publish the Docker image
      run: docker push ghcr.io/awtherllc/arelle:$RELVER
